name: suPAErnova
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.13.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - alsa-lib=1.2.3=h516909a_0
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h497a2fe_1001
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2021.10.8=py38h578d9bd_1
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - click=8.0.1=py38h578d9bd_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=10.1.243=h036e899_8
  - cudnn=7.6.5.32=hc0a50b0_1
  - cupti=10.1.168=0
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_1
  - dbus=1.13.6=h48d8840_2
  - decorator=5.0.9=pyhd8ed1ab_0
  - expat=2.4.1=h9c3ff4c_0
  - extinction=0.4.6=py38h6c62de6_1
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - gast=0.3.3=py_0
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - google-auth=1.30.2=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.38.0=py38hdd6454d_0
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - h5py=2.10.0=nompi_py38h9915d05_106
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.5.0=py38h578d9bd_0
  - ipykernel=5.5.5=py38hd0cf306_0
  - ipython=7.24.1=py38hd0cf306_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py38h578d9bd_2
  - jpeg=9d=h36c2ea0_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.19.1=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.77.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.3=h3e27bee_0
  - libgomp=11.2.0=h1d223b6_12
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=9_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.15=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.17.2=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - matplotlib=3.4.2=py38h578d9bd_0
  - matplotlib-base=3.4.2=py38hcc49a3a_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - multidict=5.1.0=py38h497a2fe_1
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - ncurses=6.2=h58526e2_4
  - nspr=4.30=h9c3ff4c_0
  - nss=3.67=hb5efdd6_0
  - numpy=1.20.3=py38h9894fe3_1
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - pandas=1.2.5=py38h1abd341_0
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py38ha0e1e83_1
  - pip=21.1.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - protobuf=3.17.2=py38h709712a_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.10=h49503c6_1_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=22.1.0=py38h2035c66_0
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scipy=1.6.3=py38h7b17777_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.35.5=h74cdb3f_0
  - statsmodels=0.12.2=py38h5c078b8_0
  - tensorboard=2.5.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py38h2b97feb_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorflow=2.2.0=gpu_py38hb782248_0
  - tensorflow-base=2.2.0=gpu_py38h83e3d50_0
  - tensorflow-estimator=2.5.0=pyh81a9013_1
  - termcolor=1.1.0=py_2
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.0.5=py_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.12.1=py38h497a2fe_3
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yarl=1.6.3=py38h497a2fe_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - astropy==5.0.1
    - cloudpickle==1.3.0
    - joblib==1.1.0
    - packaging==21.3
    - pyerfa==2.0.0.1
    - pyyaml==6.0
    - ruamel-yaml==0.17.9
    - ruamel-yaml-clib==0.2.2
    - scikit-learn==1.0.2
    - sncosmo==2.7.0
    - tensorflow-addons==0.11.2
    - tensorflow-probability==0.10.1
    - threadpoolctl==3.1.0
prefix: /global/homes/g/gstein/.conda/envs/suPAErnova

